name: Setup yt-dlp
description: Setup/Install yt-dlp (a youtube-dl fork) for GitHub Actions
branding:
  icon: play-circle
  color: red
  
runs:
  using: composite
  steps:
    - name: Install yt-dlp using pip3
      shell: bash
      run: pip3 install yt-dlp