name: Setup yt-dlp
description: Setup/Install yt-dlp (a youtube-dl fork) for GitHub Actions
branding:
  icon: play-circle
  color: red
inputs:
  with-ffmpeg:
    description: Install FFmpeg for yt-dlp
    required: false
    default: false
    
runs:
  using: composite
  steps:
    - name: Download yt-dlp/FFmpeg-Builds for Linux
      if: inputs.with-ffmpeg == 'true' && runner.os == 'linux'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/Download-yt-dlp-FFmpeg-Linux.sh
      
    - name: Install yt-dlp/FFmpeg-Builds on tool cache
      if: inputs.with-ffmpeg == 'true' && runner.os == 'linux'
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: yt-dlp-ffmpeg
        
    - name: Setup FFmpeg using FedericoCarboni/setup-ffmpeg for Windows and macOS
      if: inputs.with-ffmpeg == 'true' && (runner.os == 'windows' || runner.os == 'macos')
      uses: FedericoCarboni/setup-ffmpeg@v1
      
    - name: Install yt-dlp using pipx
      shell: bash
      run: pipx install yt-dlp