name: Setup yt-dlp-youtube-oauth2
description: Setup/Install YouTube OAuth2 yt-dlp plugin for GitHub Actions
branding:
  icon: play-circle
  color: red
inputs:
  version:
    description: yt-dlp-youtube-oauth2 version
    default: latest
  token_data:
    description: OAuth2 token data encoded in Base64
    default: false
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
  token-data:
    description: OAuth2 token data encoded in Base64 (deprecated)
    default: false
    
runs:
  using: composite
  steps:
    - name: Get yt-dlp-youtube-oauth2 version for Unix-like
      id: version-unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version/Unix-like.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Download and install yt-dlp-youtube-oauth2 for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/download/Unix-like.sh
      env:
        version: ${{ steps.version-unix-like.outputs.version }}
        
    - name: Sign in to yt-dlp-youtube-oauth2 on Unix-like
      if: (runner.os == 'Linux' || runner.os == 'macOS') && inputs.token_data != 'false'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      env:
        token_data: ${{ inputs.token_data || inputs.token-data }}