name: Setup yt-dlp YouTube OAuth
description: Setup YouTube OAuth refresh token for GitHub Actions
branding:
  icon: play-circle
  color: red
inputs:
  refresh_token:
    description: OAuth refresh token encoded in Base64
    required: true
    
runs:
  using: composite
  steps:
    - name: Sign in to YouTube OAuth for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/Unix-like.sh
      env:
        refresh_token: ${{ inputs.refresh_token }}
        
    - name: Sign in to YouTube OAuth for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\Windows.ps1'
      env:
        refresh_token: ${{ inputs.refresh_token }}