name: Update yt-dlp YouTube OAuth
description: Update YouTube OAuth refresh token for GitHub Actions
branding:
  icon: play-circle
  color: red
inputs:
  refresh_token_secret_name:
    description: OAuth refresh token secret name on GitHub
    default: YOUTUBE_OAUTH_REFRESH_TOKEN
  token:
    description: GitHub personal access token that has read and write access to secrets scope to update secret
    required: true
    
runs:
  using: composite
  steps:
    - name: Update YouTube OAuth refresh token for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: base64 < ~/.cache/yt-dlp/youtube/oauth_refresh_token_default.json | gh secret set "$refresh_token_secret_name"
      env:
        refresh_token_secret_name: ${{ inputs.refresh_token_secret_name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}
        
    - name: Update YouTube OAuth2 token data for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '[Convert]::ToBase64String([IO.File]::ReadAllBytes("$env:USERPROFILE\.cache\yt-dlp\youtube\oauth_refresh_token_default.json")) | gh secret set "$env:refresh_token_secret_name"'
      env:
        refresh_token_secret_name: ${{ inputs.refresh_token_secret_name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}