name: Test setup-yt-dlp/oauth
on:
  push:
    paths:
      - oauth/action.yaml
      - oauth/scripts/**
      - oauth/update-token/action.yaml
      - .github/workflows/test-oauth.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Setup yt-dlp using setup-yt-dlp
        uses: AnimMouse/setup-yt-dlp@main
        with:
          with-ffmpeg: ${{ runner.os != 'macOS' }}
          
      - name: Setup yt-dlp YouTube OAuth using setup-yt-dlp/oauth
        uses: AnimMouse/setup-yt-dlp/oauth@main
        with:
          refresh-token: ${{ secrets.YOUTUBE_OAUTH_REFRESH_TOKEN }}
          
      - name: Test yt-dlp by downloading a test video
        run: yt-dlp -P yt-dlp-test-video --restrict-filenames --username oauth --password "" https://www.youtube.com/watch?v=BaW_jenozKc
        
      - name: Update yt-dlp YouTube OAuth refresh token using setup-yt-dlp/oauth/update-token
        uses: AnimMouse/setup-yt-dlp/oauth/update-token@main
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Upload yt-dlp test video
        uses: actions/upload-artifact@v4
        with:
          name: yt-dlp test video
          path: yt-dlp-test-video
          if-no-files-found: error