name: Test setup-yt-dlp
on:
  push:
    paths:
      - action.yml
      - .github/workflows/test.yml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ffmpeg: [without-ffmpeg, with-ffmpeg]
        
    steps:
      - name: Setup FFmpeg
        if: matrix.ffmpeg == 'with-ffmpeg' && (runner.os == 'windows' || runner.os == 'macos')
        uses: FedericoCarboni/setup-ffmpeg@v1
        
      - name: Setup yt-dlp using setup-yt-dlp
        uses: AnimMouse/setup-yt-dlp@main
        with:
          with-ffmpeg: ${{ matrix.ffmpeg == 'with-ffmpeg' }}
          
      - name: Test yt-dlp installed by setup-yt-dlp
        run: yt-dlp https://www.youtube.com/watch?v=BaW_jenozKc
        
      - name: List files
        run: ls