name: Update tag
on:
  workflow_dispatch:
    branches:
      - main
      
jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: v1